export const executiveTeam = [
  { name: "Gaurav Kohli",        role: "Founder & CEO",                       image: "/images/about-us/team/gaurav.png",   linkedin: "https://www.linkedin.com/in/ginnykohli/",              bio: "Gaurav is a serial entrepreneur and technologist with $350M in exits across three companies, sold to Cox Automotive, HW Media, and Fox Rent-A-Car. He previously served as Chief Product & Technology Officer at Fox Rent-A-Car and Europcar, where he delivered over 20x returns in four years." },
  { name: "Raj Kondapalli",      role: "Founder & CTO",                   image: "/images/about-us/team/raj.png",      linkedin: "https://www.linkedin.com/in/rajkondapalli/",           bio: "Raj brings over 20 years in health tech, building and scaling major platforms. He launched a CDC COVID-19 tracker used by more than 60 million patients, exited Quirk.ai to SAP, and drove $10M+ in revenue at Roche." },
  // { name: "Abhit Singh MD",   role: "Chief Medical Advisor",               image: "/images/about-us/team/abhit.png",    linkedin: "",                                                     bio: "" },
  { name: "Sean Busking",        role: "Chief Operating Officer",             image: "/images/about-us/team/sean.png",    linkedin: "https://www.linkedin.com/in/seanbusking/",             bio: "Sean is an experienced operating executive who served as COO of Fox Rent-A-Car, leading sales and operations and growing the company from $100M to $450M. He was also CEO of Airport Van Rentals." },
  { name: "David Sturtz",        role: "Chief Marketing Officer",             image: "/images/about-us/team/david.png",   linkedin: "https://www.linkedin.com/in/davidesturtz/",            bio: "David is a repeat entrepreneur, marketer, and leader. He founded RepairPal, which exited to Yelp for $80M, and has served as CMO and Head of Business Development for software companies representing over $500M in exits. He is a Berkeley and Stanford Engineering alum, and a former Wall Street analyst." },
  { name: "Wilma Rodriguez-Griffith", role: "Field Operations",               image: "/images/about-us/team/wilma.png",   linkedin: "https://www.linkedin.com/in/wilma-ramirez/",           bio: "Wilma's decades of healthcare experience and focus on people make her a strong implementation and support leader at VitalFriend. She wears many hats, including executive support, healthcare operations, patient coordination, and residential care.",  hoverColor: "#FBB7FF" },
  { name: "Chan",                role: "Director of Sales, East Region",      image: "/images/about-us/team/chhan.png",   linkedin: "",                     bio: "Chan brings over 20 years in the medical field as an owner-operator of nursing homes, assisted living facilities, and sober living homes. He holds a degree in advertising, marketing, and business." },
  { name: "Abdullah",            role: "Software Engineer",                            image: "/images/about-us/team/abdullah-default.png",linkedin: "https://www.linkedin.com/in/afoysal00/",               bio: "Abdullah is a software engineer at VitalFriend., working remotely in Dart and the Postman API. A dedicated educator, he taught for five years at Apian Tutorials and served as a TA for Discrete Structures at Hunter College. He was named a Google G-SWEP Fellow, one of 80 from 350+ applicants." },
  { name: "Ekta Gulati",         role: "Director of Product - Software",      image: "/images/about-us/team/ekta.png",    linkedin: "https://www.linkedin.com/in/ekta-gulati-1521915/",     bio: "Ekta is a product executive in SaaS and AI, as Head of Product – Software at VitalFriend. With an MBA from Kellogg, she led product for AI at AuditBoard and held principal and senior roles at LivePerson and Medallia, specializing in turning technology into revenue-generating growth.",                hoverColor: "#FBB7FF" },
  { name: "Andrea Hellebuyck",   role: "Marketing",                           image: "/images/about-us/team/andrea.png",  linkedin: "https://www.linkedin.com/in/andreahellebuyck/",        bio: "Andrea is a marketing leader with 15+ years building brands people actually remember. Her work spans fashion, beauty, CPG, hospitality, and health tech, from Director-level roles at RVCA and Vitamin A Swimwear to co-founding a digital marketing agency.",           hoverColor: "#FBB7FF" },
  { name: "Bijal Shah",          role: "Director of Product - Hardware",       image: "/images/about-us/team/bijal.png",   linkedin: "https://www.linkedin.com/in/bijal-shah-2215391/",      bio: "Bijal is a product strategy leader focused on wearable health technology and remote patient monitoring. As Head of Product – Hardware at VitalFriend, he owns the roadmap for Vital Buddy, a wrist-worn platform for blood pressure tracking and senior-care workflows. He brings 20+ years turning complex technology into practical, scalable products." },
  { name: "Kevin Golchin",       role: "Chief Information Security Officer",  image: "/images/about-us/team/kevin1.png", linkedin: "https://www.linkedin.com/in/kevingolchin/",            bio: "Kevin is a cybersecurity leader with 25+ years in enterprise security, cloud transformation, and compliance across SOC 2, NIST, ISO 27001, PCI, GDPR, and CPRA. He embeds DevSecOps and AI-driven automation into the development lifecycle. Previously: Napster, AEG, Europcar." },
  { name: "John Majeski",        role: "Chief of Staff",                      image: "/images/about-us/team/john.png",    linkedin: "https://www.linkedin.com/in/johnmajeski/",             bio: "John is a product and technology executive who achieved #1 worldwide market share at his last three companies. Taking a voice-of-customer, data-driven approach, he builds top-rated teams and drives profitability, margin improvement, and differentiated product lines." },
  { name: "Anthony K. Voorhies", role: "Chief Commercial Officer",            image: "/images/about-us/team/anthony.png", linkedin: "https://www.linkedin.com/in/anthony-voorhies-6422a134/", bio: "Anthony is a healthcare and biotech executive with 25+ years of experience, leading all commercial ventures for VitalFriend. He's led precision diagnostics deployments and built CLIA CAP labs from the ground up, driving revenue and expanding global testing access." },
  { name: "Emad Hawatmeh",       role: "Chief of Uniformed Services",         image: "/images/about-us/team/emad.jpg",    linkedin: "",                                                     bio: "Emad serves as Chief of Uniformed Services at VitalFriend, bringing over a decade of progressive leadership and operational experience in uniformed services. Recognized for his strategic leadership and integrity, he drives initiatives that strengthen service delivery, accountability, and community trust across complex operations." },
  { name: "Shiv Chadha",         role: "Data & Marketing",                    image: "/images/about-us/team/shiv.png",    linkedin: "https://www.linkedin.com/in/shivchadha4/",             bio: "Shiv is a recent graduate from the University of San Francisco, currently an intern at VitalFriend, focused on turning data into strategic decisions. His experience spans marketing analytics, CRM analysis, and dashboard development across sales and growth funnels." },
];

export const advisors = [
  { name: "Adam Galper",                  bio: "AI expert, technical entrepreneur/founder of software companies.", image: "/images/about-us/advisors/adam.png",    linkedin: "https://www.linkedin.com/in/adamgalper/" },
  { name: "Dr. Sheryl Neelankavil Jose",  bio: "Physician, Seasoned health care executive and entrepreneur.", image: "/images/about-us/advisors/sheryl.png",  linkedin: "https://www.linkedin.com/in/dr-sheryl-neelankavil-jose-1a563a106/"},
  { name: 'William "Will" Patterson, RN', bio: "Founder of Carerev (YCombinator Company).", image: "/images/about-us/advisors/william.png", linkedin: "https://www.linkedin.com/in/william-patterson-6ba354b6/"},
  { name: "Ole Eichhorn",                 bio: "EVP Paypal, CTO InTouch Health, CTO Teledoc, Founder Eyesfinder.", image: "/images/about-us/advisors/ole.png",     linkedin: "https://www.linkedin.com/in/oleeichhorn/"},
  {name: "Dr. Rohan Nagar",               bio:"World renowned Ayurvedic Consultant, Educator, and Health Coach.", image: "/images/about-us/advisors/nagar.png", linkedin: "https://www.linkedin.com/in/rohan-nagar-2587a51a8/", circleBg: true},
  {name: "David Choi",               bio:"Faculty Director Entrepreneurship Business Center - Loyola Marymount University.", image: "/images/about-us/advisors/Choi.png", linkedin: "https://www.linkedin.com/in/david-y-choi-13499/", circleBg: true},
  {name: "Donna Lee",               bio:"StartUp, Corporate and Entrepreneur Lawyer.", image: "/images/about-us/advisors/Leee.png", linkedin: "https://www.linkedin.com/in/donna-lee-69709854/", circleBg: true},
  { name: "Bob Karr",                     bio: "CEO/Founder LinkSV, angel investor, venture partner.", image: "/images/about-us/advisors/bob1.png",    linkedin: "https://www.linkedin.com/in/bobkarr/"},
  // {name: "Gary Goldman",               bio:"Founding Partner and CEO @ Global Health Impact Network & Funds.", image: "", linkedin: "https://www.linkedin.com/in/garygoldman-md-dds-mba/"},

];
